# -*- coding: utf-8 -*-
"""Demo222_Filter_Nature_Duplicates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMvTS7YojMHmD_e4EX_T1o7wIunktnG2

## Duplicated features

* Both features are identical 
* Sometimes added after OHE 
* Remove duplicates
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

from google.colab import drive
drive.mount("/content/gdrive")
data = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/FeatureSelection/train_santander.csv', nrows = 5000)
y = data.TARGET
X = data.drop(columns=['TARGET'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

X_train.shape, X_test.shape

"""## Removing duplicate features"""

[col for col in data.columns if data[col].isnull().sum() > 0]

"""### Duplicates using Pandas

* Transpose 
* Find 
* Remove 

"""

X_train.head()

X_train = X_train.T
X_train.head()

X_train.duplicated().sum()

X_train[X_train.duplicated()]

duplicates = X_train[X_train.duplicated()].index.values
duplicates

X_train = X_train.drop_duplicates(keep='first').T
X_train.shape